#!/usr/bin/python3

__requires__ = 'calltest'
import re
import sys
import os
sys.path[0:0] = (".","../python-asyncari")

try:
    from pkg_resources import load_entry_point
except Exception as exc:
    pass
else:
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('calltest', 'console_scripts', 'calltest')())

from calltest.command import cmd
cmd()

